### ISSUE TITLE
Which box exactly?

### ISSUE THREAD

**Issue by mohlek** [Aldohrs/tahoma-jailbreak#1]
I have noticed there are several tahoma boxes available.
Which box does this guide belongs to?

I have several roller shutter from somfy installed and want to have real control over it. For now I don't own a tahoma box but I am considering to get one and root it so I can use it with home assistant properly.

**Comment by Aldohrs** [comment]
Hello @mohlek,

The box I have and on which I tested everything is the Somfy TaHoma also code named Kizbox V2 internally.

It looks like this: 

![tahoma](https://user-images.githubusercontent.com/58393088/103177184-0efe0e80-4870-11eb-9958-ce17e7213681.jpeg)

I think the process could work with any Kizbox revision based on the AT91 series (provided a test point is available for the CE# pin as it is difficult to poke a 0,5mm wide pin). You can have an idea of which ones by following this link: https://github.com/torvalds/linux/search?q=overkiz

At the moment, there is no actual usable solution developed to use any Somfy io-homecontrol gateway without their cloud servers. The TaHoma integration in Home Assistant uses the public-facing cloud API from Somfy. So if you don't mind using Somfy's cloud, you can already integrate it to your Home Assistant instance. More information here: https://www.home-assistant.io/integrations/tahoma/

**Comment by mohlek** [comment]
thanks for your reply.
I know about the cloud integration with home assistant but this is no viable solution for me. Not everything is properly exposed via the cloud api. The enocean devices are not exposed at all.

I dont mind putting some effort in it to get a local api or something like this.
Maybe I take a look at it and would be happy to support your work to replace the somfy cloud.

**Comment by iMicknl** [comment]
> thanks for your reply.
> I know about the cloud integration with home assistant but this is no viable solution for me. Not everything is properly exposed via the cloud api. The enocean devices are not exposed at all.

You could use https://github.com/imicknl/ha-tahoma as well, it supports (almost) all devices that are available on tahomalink.com! :-). 

> I dont mind putting some effort in it to get a local api or something like this.
> Maybe I take a look at it and would be happy to support your work to replace the somfy cloud.

I would love this as well, especially since HomeKit support has been added recently, which means they need to have some sort of local API... However, I am not able to dump the firmware like you did, to see if we can reverse engineer something.

At least we were able to receive the HomeKit code + authentication, perhaps we can run some kind of local HomeKit controller to use that local API. (which only supports a few devices..)

**Comment by Aldohrs** [comment]
I documented the complete codename: Kizbox V2 with 2 heads (also tahoma2-2 as seen in DTS files). The CozyTouch, aka Kizbox mini, has many similarities.
