### ISSUE TITLE
No sources for TaHoma. GPL Violation?

### ISSUE THREAD

**Issue by Velocet** [Aldohrs/tahoma-jailbreak#4]
I was just wondering if it presents a GPL violation that there are no build-tools or otherwise sources for the TaHoma/Overkiz boxes.

What do you think?

**Comment by Aldohrs** [comment]
Hi,

I don't think there is any GPL violation here. I'm not an expert but Overkiz developers committed code to the mainline Linux Kernel on top of device trees (actually large parts of code for SAM drivers). Build options of the Kernel used by Overkiz  are mostly unknown but I don't think open sourcing them is required by the license. I was able to compile a custom Kernel without patching the code.
